### PR TITLE
Activate extension when .graphqlconfig is detected

### PR DESCRIPTION
**Pull request by lostplan**
Fix for https://github.com/stephen/vscode-graphql/issues/7

### CODE REVIEW

**Comment by stephen** [comment]
Thanks for looking into this.

I worry that without fixing https://github.com/stephen/vscode-graphql/issues/8, we'll see some folks have the extension installed but still see errors that are not obviously fixable.

**Comment by lostplan** [comment]
Ah yes, good point. That seems quite important to fix – I'll try to find some time to work on it.

**Comment by stephen** [comment]
can't think of any reasons why we shouldn't do this now. wdyt, @lostplan?

**Comment by lostplan** [comment]
Yeah it would be great to merge this

**Comment by stephen** [comment]
released in 0.2.3.

**Pull request merged**
